# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
latex: false
pandoc: false


r_github_packages:
- jimhester/covr

after_success:
- Rscript -e 'library(covr);codecov()'

r:
  - oldrel
  - release
  - devel

env:
  # MENDELEY_CLIENT_ID="****"
  - secure: "YznzscJYWtlS9trxjwT/6wtI16SWhh/30ZOrOB6SVagv1LoAjRlGRz3ybNYtesGaOA6ogmeYRwn4KuB99K6GET82MEpJQfqMGCakVWVlLEdu9/IGAbIdHBUbkEmaRpPA8Y6jSfaJxxnb0KOVK2AIlmJ84aRtqIDBMJ8qtOdqWgi+2+Wk7duU4LPpWXs2L7XVUIZnjzBbcaf8Xwe4VmGDsONOk9zISJqfKPbAwoZz2F2xbA9CsGTdrNRwl1IdCe6TL08ftAMG+1sKTnfNyPZQj3GAsGTVQYazgZmWrtCoWPMWURqZhGxRLsJmqmoZKAfhXzboITImIGvtU6ZOKkgsLfV1Dt4GZnMeCHrSzLEbrYpucsWTe/DIH0AxzvjGkHZkzU1HFB43vhKAn2MByaPp59OufciCtyyZvZmkY1EP0ZLrBiQK1jRQAGrWIjjsMLqZcedJn3tUaam8U9ooitPIPcFHUxqFJqqhadzhbAY3yUrAtVeGGglNgOxXBwVWXl2tApY3+zYVDLoL/m35M4NWNiVfGn3AnAzSSyyoM13BDrqAP7px8G7qFZ6aSFWS74cANzUOC4drM1aJhmxrbs5SpuEjpZx5qNHQ8s5gSDMz8bUP0xCvIUHwzgi/a4DYL7YK1auyfiWEZSrl7uvnfRcKcVAUsH1BYPcSA+KGYq3BhIc="
  # MENDELEY_CLIENT_SECRET="****"
  - secure: "P6AcSlFIxMsYfXZViFbc10e1s96je/oGLg1vHCIWQAcguchUP2hmiDoJFqPnbkLmMSxE14lAiEE+RCvjA/A4I9gbQ8T9aEN64kZh5gYG+4nO6gF8FNJAqcVwmJwHozWgZDbr3/VNwyV+hXJr5QQm0sHKQo+t/ItdfugJ3ou2p1QJr1iMGCKeWMSb1QkczoeJ5Uk19jO1LCvLLbkabbjN6pVc99UEZh/7p+Q5Q6ZJ3ebKeH2Hkj4Vkc8ef34ddDYdwkyHlRONe874EiPUw/FVi1kLe0Vuq4FGSepjhnNTIWORN/fXH0/I5zKYwsSmB2YCrfw6fpI13I1/jY45Um0SbwSwUakdrYs8CxucqWyy8VuTXIAiVfAf6M5pBtAep2i4dcMmh/9wFqa+ZPvz8RMSB5gQyHCh7CKgqSq1bbNLSljohVHtzM9m9EhXvTkvcpolBL2tQcjYR9pYWd04NVJK4ETfaG3VeS8APbcBQPoAkjWLQYRqmSHnOJwDMhkt4HucVR3BN9VK4DDHk/MPZBtpJrzEEngkbG+DJqnlOsLO12CzS3/Y0UErYPcdi0vN0G/a+Ey4DQIuYnOiaMmFGxFPenXFEvTOvdf4/TWz9e5vHkrB07Q77vOVEDvW3KFeqoj3ptm2BHFaq1jlBV0Olf4DSCkM/cg6IVQfUU1OtZ/xDhc="

# Token credentials to my test account
before_install:
  - openssl aes-256-cbc -K $encrypted_14d0ef99bd92_key -iv $encrypted_14d0ef99bd92_iv -in .httr-oauth.enc -out .httr-oauth -d
